services:
  sync_redis:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379

