name: Redis Sync

on:
  schedule:
    # every 10 minutes
    - cron: '*/10 * * * *' 
  workflow_dispatch: # 允许手动触发

permissions:
  actions: write
  contents: read

jobs:
  RedisSync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Main File
      run: python3 main.py
      env:
        SOURCE_REDIS_HOST: ${{ secrets.SOURCE_REDIS_HOST }}
        SOURCE_REDIS_PORT: ${{ secrets.SOURCE_REDIS_PORT }} 
        SOURCE_REDIS_USERNAME: ${{ secrets.SOURCE_REDIS_USERNAME }} 
        SOURCE_REDIS_PASSWORD: ${{ secrets.SOURCE_REDIS_PASSWORD }} 
        SOURCE_REDIS_SSL: ${{ secrets.SOURCE_REDIS_SSL }} 
        SOURCE_REDIS_PROTOCOL: ${{ secrets.SOURCE_REDIS_PROTOCOL }} 

        DEST_REDIS_HOST: ${{ secrets.DEST_REDIS_HOST }} 
        DEST_REDIS_PORT: ${{ secrets.DEST_REDIS_PORT }} 
        DEST_REDIS_USERNAME: ${{ secrets.DEST_REDIS_USERNAME }} 
        DEST_REDIS_PASSWORD: ${{ secrets.DEST_REDIS_PASSWORD }} 
        DEST_REDIS_SSL: ${{ secrets.DEST_REDIS_SSL }} 
        DEST_REDIS_PROTOCOL: ${{ secrets.DEST_REDIS_PROTOCOL }} 

    - name: Delete old workflow runs
      uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        repository: ${{ github.repository }}
        # 删除 1 天前的 workflow 运行
        older-than-seconds: 86400
